project:
  type: website
  output-dir: "docs"
  lib-dir: "docs/site_libs"

execute:
  freeze: auto

website:
  title: "Vino Wang"
  description: "PhD student in Learning, Design, and Technology focused on GenAI in education, educational data science, and evaluation methods."
  image: vino.png
  favicon: vino.png
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: Projects.qmd
      - text: "Publications"
        file: Publications.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "Blogs"
        file: Blogs.qmd
      - text: "Teaching"
        file: Teaching.qmd
      - text: "CV"
        file: CV.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
     # - icon: twitter
       # href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css
    open-graph: true
    twitter-card: true

editor: visual

